### ISSUE TITLE
Clobbering an existing purescript library

### ISSUE THREAD

**Issue by ehrenmurdick** [bklaric/purescript-jarilo#1]
Hi there,

Your package name is the same as mine, which I've already published to pursuit. So the docs page is getting clobbered. 

Since I first published mine quite a long time ago, do you mind changing yours?

https://pursuit.purescript.org/packages/purescript-oak/0.1.7
https://github.com/ehrenmurdick/purescript-oak

**Comment by ehrenmurdick** [comment]
Nvm, I see that you already renamed it. Sorry!

I'll just have to bump my version to 0.4.0 so that it doesn't say yours is the latest version. I'll send an issue to the pursuit maintainers as well.

Thanks!

**Comment by bklaric** [comment]
Sorry about that, I missed that the name was already taken. I hope this won't cause you too much trouble.

**Comment by ehrenmurdick** [comment]
No worries! I see there's already an issue up for the pursuit maintainers so they're working on it. All I had to do was bump my oak from 0.1 to 0.4 to make the docs page make sense. 

On the bright side, I think I might be able to use jarilo in my oak!

**Comment by bklaric** [comment]
Glad to hear it worked out.
